import type { PlannedWrite } from "../domain/types.js";
import { AGENT_KIT_DIR } from "../domain/types.js";
import type { ProjectModel } from "../intelligence/types.js";
import { writeFileAtomic } from "../storage/atomic-write.js";
import {
  applyFileChanges,
  createFileProbe,
  planAgentInstall,
  writeInstallManifest,
  type FileChange,
} from "../adapters/installer.js";
import type { AgentId } from "../adapters/types.js";
import path from "node:path";

/** Local-only files inside .agent-kit/ that shouldn't be committed. */
export const AGENT_KIT_GITIGNORE = "# Generated by Agent Kit\nsnapshot.json\nstate/backups/\n";

export type AgentInstallResult = {
  agents: AgentId[];
  writes: FileChange[];
  warnings: string[];
  conflicts: number;
};

/** Plan, and unless dryRun apply, the agent files for `agents`. */
export async function installAgents(options: {
  root: string;
  model: ProjectModel;
  agents: AgentId[];
  explicit: AgentId[];
  dryRun: boolean;
  now?: Date;
}): Promise<AgentInstallResult> {
  const { root, model, agents, explicit, dryRun } = options;
  const plan = await planAgentInstall(root, model, agents, explicit);

  const gitignorePath = `${AGENT_KIT_DIR}/.gitignore`;
  const existing = await createFileProbe(root).read(gitignorePath);
  const gitignore: FileChange = {
    path: gitignorePath,
    action: existing === null ? "create" : existing === AGENT_KIT_GITIGNORE ? "unchanged" : "skip",
    ...(existing !== null && existing !== AGENT_KIT_GITIGNORE ? { reason: "user-edited" } : {}),
  };

  if (!dryRun) {
    await applyFileChanges(root, plan.changes, options.now);
    await writeInstallManifest(root, plan.manifest);
    if (existing === null)
      await writeFileAtomic(path.join(root, gitignorePath), AGENT_KIT_GITIGNORE);
  }

  const writes = [...plan.changes, gitignore];
  return {
    agents,
    writes,
    warnings: plan.warnings,
    conflicts: writes.filter((w) => w.action === "conflict").length,
  };
}

/** Strip internals before handing writes to callers that print them. */
export function toPlannedWrites(changes: readonly FileChange[]): PlannedWrite[] {
  return changes.map(({ path: p, action, reason }) =>
    reason ? { path: p, action, reason } : { path: p, action },
  );
}

/** True when an install touched files outside .agent-kit/ (which the model describes). */
export function changedRepoFiles(changes: readonly FileChange[]): boolean {
  return changes.some(
    (c) =>
      !c.path.startsWith(`${AGENT_KIT_DIR}/`) &&
      ["create", "update", "remove", "delete"].includes(c.action),
  );
}
