import type { PlannedWrite } from "../domain/types.js";
import { AGENT_KIT_DIR } from "../domain/types.js";
import type { ProjectModel } from "../intelligence/types.js";
import { writeFileAtomic } from "../storage/atomic-write.js";
import {
  applyFileChanges,
  createFileProbe,
  planAgentInstall,
  writeInstallManifest,
  type FileChange,
} from "../adapters/installer.js";
import type { AgentId } from "../adapters/types.js";
import { detectConflicts } from "../rules/conflicts.js";
import { loadRules } from "../rules/rules.js";
import { isSkillDistributable, loadSkills } from "../rules/skills.js";
import path from "node:path";

/** Local-only files inside .agent-kit/ that shouldn't be committed. */
export const AGENT_KIT_GITIGNORE = "# Generated by Agent Kit\nsnapshot.json\nstate/backups/\n";

export type AgentInstallResult = {
  agents: AgentId[];
  writes: FileChange[];
  warnings: string[];
  conflicts: number;
};

/** Plan, and unless dryRun apply, the agent files for `agents`. */
export async function installAgents(options: {
  root: string;
  model: ProjectModel;
  agents: AgentId[];
  explicit: AgentId[];
  dryRun: boolean;
  approvedSkills?: Record<string, string>;
  now?: Date;
}): Promise<AgentInstallResult> {
  const { root, model, agents, explicit, dryRun } = options;
  const { rules, problems: ruleProblems } = await loadRules(root);
  const { skills, problems: skillProblems } = await loadSkills(root);
  const ready = skills.filter((s) => isSkillDistributable(s, options.approvedSkills));
  const pending = skills.filter((s) => !isSkillDistributable(s, options.approvedSkills));

  const plan = await planAgentInstall(root, model, agents, explicit, { rules, skills: ready });
  const notes = [
    ...ruleProblems.map((p) => `Rule skipped: ${p.source}: ${p.message}`),
    ...skillProblems.map((p) => `Skill skipped: ${p.source}: ${p.message}`),
    ...pending.map(
      (s) =>
        `Skill "${s.name}" contains executable files (${s.scripts.slice(0, 3).join(", ")}${s.scripts.length > 3 ? ", …" : ""}). ` +
        `Review it, then run \`agent-kit skills approve ${s.name}\` to install it.`,
    ),
  ];

  const gitignorePath = `${AGENT_KIT_DIR}/.gitignore`;
  const existing = await createFileProbe(root).read(gitignorePath);
  const gitignore: FileChange = {
    path: gitignorePath,
    action: existing === null ? "create" : existing === AGENT_KIT_GITIGNORE ? "unchanged" : "skip",
    ...(existing !== null && existing !== AGENT_KIT_GITIGNORE ? { reason: "user-edited" } : {}),
  };

  if (!dryRun) {
    await applyFileChanges(root, plan.changes, options.now);
    await writeInstallManifest(root, plan.manifest);
    if (existing === null)
      await writeFileAtomic(path.join(root, gitignorePath), AGENT_KIT_GITIGNORE);
  }

  const writes = [...plan.changes, gitignore];
  return {
    agents,
    writes,
    warnings: [...notes, ...plan.warnings, ...(await conflictNote(root, model))],
    conflicts: writes.filter((w) => w.action === "conflict").length,
  };
}

/** Strip internals before handing writes to callers that print them. */
export function toPlannedWrites(changes: readonly FileChange[]): PlannedWrite[] {
  return changes.map(({ path: p, action, reason }) =>
    reason ? { path: p, action, reason } : { path: p, action },
  );
}

/** True when an install touched files outside .agent-kit/ (which the model describes). */
export function changedRepoFiles(changes: readonly FileChange[]): boolean {
  return changes.some(
    (c) =>
      !c.path.startsWith(`${AGENT_KIT_DIR}/`) &&
      ["create", "update", "remove", "delete"].includes(c.action),
  );
}

async function conflictNote(root: string, model: ProjectModel): Promise<string[]> {
  const conflicts = await detectConflicts(root, model);
  if (conflicts.length === 0) return [];
  return [
    `${conflicts.length} possible conflict(s) between instruction files and the repo. Run \`agent-kit conflicts\` to review.`,
  ];
}
