export type ErrorCode =
  | "PROJECT_NOT_FOUND"
  | "INVALID_PROJECT_ROOT"
  | "ALREADY_INITIALIZED"
  | "CONFIG_INVALID"
  | "INDEX_FAILED"
  | "PERMISSION_DENIED"
  | "STORAGE_WRITE_FAILED"
  | "UNSUPPORTED_OPERATION";

export const ERROR_CODES: readonly ErrorCode[] = [
  "PROJECT_NOT_FOUND",
  "INVALID_PROJECT_ROOT",
  "ALREADY_INITIALIZED",
  "CONFIG_INVALID",
  "INDEX_FAILED",
  "PERMISSION_DENIED",
  "STORAGE_WRITE_FAILED",
  "UNSUPPORTED_OPERATION",
] as const;
