import path from "node:path";
import type { DiscoveredEntry } from "../discovery/discover.js";
import { createScanContext } from "../scanner/context.js";
import { readPackageJson } from "../scanner/package-json.js";
import type { ScanResult } from "../scanner/types.js";
import { deriveCommands } from "./commands.js";
import { analyzeGit } from "./git.js";
import { analyzeStructure } from "./structure.js";
import { analyzeTesting } from "./testing.js";
import { PROJECT_MODEL_SCHEMA_VERSION, type PackageInfo, type ProjectModel } from "./types.js";

export const PROJECT_MODEL_COMMENT =
  "Generated by Agent Kit from repository files. Regenerated by `agent-kit index`; manual edits are overwritten.";

/** Build the project model from a scan. Deterministic: same tree, same model. */
export async function buildProjectModel(
  scan: ScanResult,
  entries: readonly DiscoveredEntry[],
): Promise<ProjectModel> {
  const scratch: string[] = []; // scan already reported warnings for these files
  const rootEntries = new Set<string>();
  const ctxFor = (dir: string) =>
    createScanContext({ dir, entries, rootEntries, warnings: scratch });
  const { detections, workspaces } = scan;

  const packages: PackageInfo[] = [];
  for (const location of [".", ...workspaces]) {
    const ctx = ctxFor(location);
    const pkg = await readPackageJson(ctx);
    if (!pkg && location !== ".") continue;
    packages.push({
      location,
      name: typeof pkg?.name === "string" ? pkg.name : null,
      commands: await deriveCommands(ctx, detections),
    });
  }

  const structure = analyzeStructure(entries, detections, workspaces);
  const unique = (ids: string[]) => [...new Set(ids)];

  return {
    $comment: PROJECT_MODEL_COMMENT,
    schemaVersion: PROJECT_MODEL_SCHEMA_VERSION,
    project: {
      name: packages[0]?.name ?? path.basename(scan.root),
      languages: unique(detections.filter((d) => d.category === "language").map((d) => d.id)),
      packageManager: detections.find((d) => d.category === "packageManager")?.id ?? null,
      frameworks: unique(detections.filter((d) => d.category === "framework").map((d) => d.id)),
      monorepo: workspaces.length > 0,
    },
    packages,
    structure: { directories: structure.directories, unclassified: structure.unclassified },
    architecture: structure.architecture,
    testing: analyzeTesting(entries, detections, structure.directories),
    git: analyzeGit(ctxFor("."), detections),
    detections,
    warnings: scan.warnings,
  };
}
