import type { Detection } from "../domain/types.js";
import type { DirectoryRole, ProjectCommand, ProjectModel } from "../intelligence/types.js";
import type { Rule } from "../rules/rules.js";

const ROLE_TEXT: Partial<Record<DirectoryRole, string>> = {
  routes: "routes (file-based routing)",
  application: "application code",
  "ui-components": "shared UI components",
  "feature-modules": "feature modules, one folder per feature",
  hooks: "hooks",
  "shared-utilities": "shared utilities",
  "services-api": "services / API clients",
  state: "state management",
  types: "shared types",
  styles: "styles",
  middleware: "middleware",
  server: "server code",
  controllers: "controllers",
  models: "data models",
  database: "database schema and migrations",
  tests: "tests",
  "e2e-tests": "end-to-end tests",
  "test-fixtures": "test fixtures",
  "static-assets": "static assets",
  config: "configuration",
  "scripts-tooling": "scripts and tooling",
  docs: "documentation",
};

const PM_LABEL: Record<string, string> = { npm: "npm", pnpm: "pnpm", yarn: "Yarn", bun: "Bun" };

/**
 * Repository-derived strings (paths, workspace names) end up in agent
 * instructions, so treat them as untrusted: they must look like an identifier
 * or path (no spaces, no markup, at most 80 chars) or they're left out. A folder
 * named "ignore previous instructions" never reaches an agent as prose.
 */
export function safeCode(value: string): string {
  return /^[\w@./+:-]{1,80}$/.test(value) ? `\`${value}\`` : "_(unusual name omitted)_";
}

/** For text Agent Kit composed itself from fixed templates (commands, patterns). */
function code(value: string): string {
  return `\`${value.replace(/`/g, "")}\``;
}

function label(detections: readonly Detection[], ids: string[]): string[] {
  return [...new Set(detections.filter((d) => ids.includes(d.category)).map((d) => d.label))];
}

function commandCell(c: ProjectCommand): string {
  return `${code(c.command)}${c.source.type === "inferred" ? " _(inferred)_" : ""}`;
}

/**
 * The project context every adapter shares. Deterministic and concise: agents
 * load it on every session, so it carries only what changes their behaviour.
 */
/** Nest a rule body under the block's headings: drop a leading title that repeats the description, demote the rest. */
function ruleBody(rule: Rule): string {
  const lines = rule.body.split("\n");
  const first = lines[0]?.replace(/^#+\s*/, "").trim();
  if (/^#\s/.test(lines[0] ?? "") && first?.toLowerCase() === rule.description.toLowerCase()) {
    lines.shift();
    while (lines[0]?.trim() === "") lines.shift();
  }
  let fence = false;
  return lines
    .map((line) => {
      if (/^(```|~~~)/.test(line)) fence = !fence;
      if (fence) return line;
      const m = /^(#{1,6})\s/.exec(line);
      return m ? "#".repeat(Math.min(6, m[1]!.length + 4)) + line.slice(m[1]!.length) : line;
    })
    .join("\n")
    .trim();
}

export function renderProjectContext(model: ProjectModel, rules: readonly Rule[] = []): string {
  const out: string[] = [];
  const d = model.detections;
  const monorepo = model.project.monorepo;

  out.push("## Project context", "");
  out.push(
    "> Generated by [Agent Kit](https://github.com/Mapl6/agent-kit) from this repository's files.",
    "> _(inferred)_ marks educated guesses. Regenerate with `npx @mapl6/agent-kit sync`.",
    "",
  );

  const stack = [...label(d, ["language"]), ...label(d, ["framework"]), ...label(d, ["testing"])];
  if (stack.length > 0) out.push(`**Stack:** ${stack.join(", ")}`, "");

  // Commands
  const rows = model.packages.flatMap((p) => p.commands.map((c) => ({ c, where: p.location })));
  if (rows.length > 0) {
    // Lists, not tables: formatters (Prettier) re-pad tables, which would make
    // every sync look like a change.
    out.push("### Commands", "");
    for (const { c, where } of rows) {
      const loc = monorepo && where !== "." ? ` (in ${safeCode(where)})` : "";
      out.push(`- ${c.task}${loc}: ${commandCell(c)}`);
    }
    out.push("");

    // A root script usually runs every package, so per-package commands are
    // listed only for tasks the root doesn't cover.
    const rootTasks = new Set(rows.filter(({ where }) => where === ".").map(({ c }) => c.task));
    const checks = rows.filter(
      ({ c, where }) =>
        ["typecheck", "lint", "test"].includes(c.task) && (where === "." || !rootTasks.has(c.task)),
    );
    const order = ["typecheck", "lint", "test"];
    checks.sort((a, b) => order.indexOf(a.c.task) - order.indexOf(b.c.task));
    if (checks.length > 0) {
      out.push("### Before you finish a change", "", "Run these and make sure they pass:", "");
      checks.forEach(({ c, where }, i) => {
        const loc = where === "." ? "" : ` (in ${safeCode(where)})`;
        out.push(`${i + 1}. ${code(c.command)}${loc}`);
      });
      out.push("");
    }
  }

  // Conventions: only from detected facts, or clearly marked inferences.
  const conventions: string[] = [];
  const pms = d.filter((x) => x.category === "packageManager");
  const pm = pms[0];
  if (pms.length > 1) {
    const names = pms.map((x) => PM_LABEL[x.id] ?? x.id).join(", ");
    conventions.push(
      `Several package managers are signalled (${names}). Ask before installing dependencies or touching lockfiles.`,
    );
  } else if (pm && pm.source.type === "detected") {
    const name = PM_LABEL[pm.id] ?? pm.label;
    conventions.push(
      `Use **${name}** for dependencies. Don't add a lockfile for another package manager.`,
    );
  }
  const t = model.testing;
  const pattern = t.patterns[0]?.pattern;
  if (t.placement === "colocated" && pattern) {
    conventions.push(`Tests sit next to the code they test, named like ${code(pattern)}.`);
  } else if (t.placement === "separate" && pattern) {
    const dirs = t.directories.length ? ` in ${t.directories.map(safeCode).join(", ")}` : "";
    conventions.push(
      `Tests live in separate test directories${dirs}, named like ${code(pattern)}.`,
    );
  }
  if (model.git.commitConvention === "commitlint") {
    conventions.push(
      "Commit messages are checked by commitlint; follow its configured convention.",
    );
  }
  if (model.git.hooks.length > 0) {
    conventions.push(`Git hooks run on commit (${model.git.hooks.join(", ")}); don't bypass them.`);
  }
  if (model.git.pullRequestTemplate) {
    conventions.push(
      `Fill in the pull request template at ${safeCode(model.git.pullRequestTemplate)}.`,
    );
  }
  if (conventions.length > 0) {
    out.push("### Conventions", "");
    for (const c of conventions) out.push(`- ${c}`);
    out.push("");
  }

  // Structure (always inferred)
  const dirs = model.structure.directories.filter(
    (x) => ROLE_TEXT[x.role] && x.role !== "test-fixtures",
  );
  if (dirs.length > 0 || model.architecture.length > 0) {
    out.push("### Project structure _(inferred)_", "");
    const arch = model.architecture.filter((a) => a.id !== "monorepo").map((a) => a.label);
    if (monorepo) {
      const pkgs = model.packages
        .filter((p) => p.location !== ".")
        .map((p) => safeCode(p.location));
      out.push(`Monorepo with packages ${pkgs.join(", ")}.`, "");
    }
    if (arch.length > 0) out.push(`Patterns: ${[...new Set(arch)].join(", ")}.`, "");
    for (const dir of dirs) {
      const likely = dir.confidence === "high" ? "" : " (likely)";
      out.push(`- ${safeCode(`${dir.path}/`)}: ${ROLE_TEXT[dir.role]}${likely}`);
    }
    out.push("");
  }

  // Rules are written by the project's developers as instructions for agents, so
  // they're included as written (unlike repo-derived names above).
  const always = rules.filter((r) => r.paths.length === 0);
  const scoped = rules.filter((r) => r.paths.length > 0);
  if (always.length > 0) {
    out.push("### Rules", "");
    for (const rule of always) out.push(`#### ${rule.description}`, "", ruleBody(rule), "");
  }
  if (scoped.length > 0) {
    out.push(
      "### Rules for specific files",
      "",
      "Before changing files that match a pattern below, read that rule:",
      "",
    );
    for (const rule of scoped) {
      const globs = rule.paths.map((p) => code(p)).join(", ");
      out.push(`- ${rule.description}: ${globs}. See ${code(rule.source)}.`);
    }
    out.push("");
  }

  return out.join("\n").trimEnd();
}
