import type { Rule } from "../rules/rules.js";
import type { Skill } from "../rules/skills.js";
import type { AgentId, FileTarget } from "./types.js";

const MAX_EXPANSION = 50;

/**
 * Expand `{a,b}` groups. Cursor `globs` and Copilot `applyTo` are
 * comma-separated lists, so a comma inside braces would split the pattern.
 * Claude Code understands braces and gets the original globs.
 */
export function expandBraces(glob: string): string[] {
  const match = /\{([^{}]*)\}/.exec(glob);
  if (!match) return [glob];
  const out: string[] = [];
  for (const option of match[1]!.split(",")) {
    out.push(
      ...expandBraces(
        glob.slice(0, match.index) + option + glob.slice(match.index + match[0].length),
      ),
    );
    if (out.length > MAX_EXPANSION) break;
  }
  return out.slice(0, MAX_EXPANSION);
}

const flat = (globs: string[]) => [...new Set(globs.flatMap(expandBraces))];

function header(rule: Rule): string {
  return `<!-- Generated by Agent Kit from ${rule.source}. Edit that file, then run "agent-kit sync". -->`;
}

const file = (adapter: AgentId, path: string, text: string): FileTarget => ({
  kind: "file",
  adapter,
  path,
  content: Buffer.from(text, "utf8"),
});

/** `.claude/rules/agent-kit/<id>.md`: `paths` is the only field Claude Code reads. */
export function claudeRule(rule: Rule): FileTarget {
  const text = [
    "---",
    "paths:",
    ...rule.paths.map((p) => `  - ${JSON.stringify(p)}`),
    "---",
    "",
    header(rule),
    "",
    rule.body,
    "",
  ].join("\n");
  return file("claude-code", `.claude/rules/agent-kit/${rule.id}.md`, text);
}

/** `.cursor/rules/agent-kit/<id>.mdc`: auto-attached to matching files. */
export function cursorRule(rule: Rule): FileTarget {
  const text = [
    "---",
    `description: ${JSON.stringify(rule.description)}`,
    `globs: ${flat(rule.paths).join(", ")}`,
    "alwaysApply: false",
    "---",
    "",
    header(rule),
    "",
    rule.body,
    "",
  ].join("\n");
  return file("cursor", `.cursor/rules/agent-kit/${rule.id}.mdc`, text);
}

/** `.github/instructions/agent-kit/<id>.instructions.md` with a comma-separated `applyTo`. */
export function copilotRule(rule: Rule): FileTarget {
  const text = [
    "---",
    `applyTo: ${JSON.stringify(flat(rule.paths).join(","))}`,
    "---",
    "",
    header(rule),
    "",
    rule.body,
    "",
  ].join("\n");
  return file("copilot", `.github/instructions/agent-kit/${rule.id}.instructions.md`, text);
}

/** Every file of a skill, copied byte for byte under `<base>/<name>/`. Never made executable. */
export function skillFiles(adapter: AgentId, base: string, skill: Skill): FileTarget[] {
  return skill.files.map((f) => ({
    kind: "file",
    adapter,
    path: `${base}/${skill.name}/${f.rel}`,
    content: f.content,
  }));
}
